spring:
  application:
    name: demo application
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    enable-spring-el-compiler: true
    mode: html
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: test_user
    password: test_user
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 2
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  redis:
    host: localhost
    port: 6379
    ssl: false
    database: 0
    password: foobared

# Server
server:
  port: 9001

# Logging
logging.file: log/demo.log
logging:
  file:
    max-history: 10
    max-size: 50MB
  level:
    root: info
    org.springframework: info
    org.thymeleaf: debug
    org.hibernate: info
    org.hibernate.SQL: debug
    com.example.demo: debug

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-server:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: redis-server

# Logging
logging.file: demo.log

# Server
server:
  port: 9000
